import worker, {
  JsTransformerConfig,
  JsTransformOptions,
  TransformResponse,
} from "metro-transform-worker";
import path from "path";

import { transform as cssInteropTransform } from "react-native-css-interop/metro/transformer";

export async function transform(
  config: JsTransformerConfig & { nativewind: Record<string, any> },
  projectRoot: string,
  filename: string,
  data: Buffer,
  options: JsTransformOptions,
): Promise<TransformResponse> {
  // If we are importing the .css file, make it an alias for the output generated by Tailwind CLI
  if (path.resolve(process.cwd(), filename) === config.nativewind.input) {
    if (options.platform === "web") {
      return worker.transform(
        config,
        projectRoot,
        filename,
        Buffer.from(config.nativewind.outputs[options.platform].js, "utf8"),
        options,
      );
    } else {
      data = Buffer.from(
        config.nativewind.outputs[options.platform!].raw,
        "utf8",
      );
    }
  }

  // Otherwise use the cssInteropTransform. It will handle JS files and composing transformers
  return cssInteropTransform(config, projectRoot, filename, data, options);
}
