import { StyleRecord } from "../types/common";
import { postCSSSerializer } from "../utils/serialize-styles";

export function outputFormatter(
  styles: StyleRecord,
  platform?: string
): string {
  const { style, media } = postCSSSerializer(styles);

  return `// This file was generated by tailwindcss-react-native. Do not edit!
const { StyleSheet } = require("react-native")
module.exports = { ${platform ? `\nplatform: '${platform},` : ""}
  styles: ${style},
  media: ${media},
}`;
}
