/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "category",
      label: "Overview",
      collapsed: false,
      items: ["overview/overview", "guides/goals"],
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/metro",
        "getting-started/expo-router",
        "getting-started/nextjs",
        "getting-started/typescript",
        "getting-started/other-bundlers",
      ],
    },
    {
      type: "category",
      label: "Core concepts",
      collapsed: false,
      items: [
        "core-concepts/tailwindcss",
        "core-concepts/states",
        "core-concepts/responsive-design",
        "core-concepts/dark-mode",
        "core-concepts/units",
        "core-concepts/quirks",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/troubleshooting",
        "guides/platforms",
        "guides/custom-components",
        "guides/theming",
        "guides/theme-values",
      ],
    },
    {
      type: "category",
      label: "Customization",
      collapsed: false,
      items: [
        "customization/configuration",
        "customization/content",
        "customization/theme",
        "customization/colors",
      ],
    },
    {
      type: "category",
      label: "API",
      collapsed: false,
      items: ["api/use-color-scheme", "api/native-wind-style-sheet"],
    },
    {
      type: "category",
      label: "Layout",
      collapsed: false,
      items: [
        "tailwind/layout/aspect-ratio",
        "tailwind/layout/container",
        "tailwind/layout/columns",
        "tailwind/layout/break-after",
        "tailwind/layout/break-before",
        "tailwind/layout/break-inside",
        "tailwind/layout/box-decoration-break",
        "tailwind/layout/box-sizing",
        "tailwind/layout/display",
        "tailwind/layout/floats",
        "tailwind/layout/clear",
        "tailwind/layout/isolation",
        "tailwind/layout/object-fit",
        "tailwind/layout/object-position",
        "tailwind/layout/overflow",
        "tailwind/layout/overscroll-behavior",
        "tailwind/layout/position",
        "tailwind/layout/top-right-bottom-left",
        "tailwind/layout/visibility",
        "tailwind/layout/z-index",
      ],
    },
    {
      type: "category",
      label: "Flexbox & Grid",
      collapsed: false,
      items: [
        "tailwind/flexbox/flex-basis",
        "tailwind/flexbox/flex-direction",
        "tailwind/flexbox/flex-wrap",
        "tailwind/flexbox/flex",
        "tailwind/flexbox/flex-grow",
        "tailwind/flexbox/flex-shrink",
        "tailwind/flexbox/order",
        "tailwind/flexbox/gap",
        "tailwind/flexbox/order",
        "tailwind/flexbox/grid-template-columns",
        "tailwind/flexbox/grid-column",
        "tailwind/flexbox/grid-template-rows",
        "tailwind/flexbox/grid-row",
        "tailwind/flexbox/grid-auto-flow",
        "tailwind/flexbox/grid-auto-columns",
        "tailwind/flexbox/grid-auto-rows",
        "tailwind/flexbox/justify-content",
        "tailwind/flexbox/justify-items",
        "tailwind/flexbox/justify-self",
        "tailwind/flexbox/align-content",
        "tailwind/flexbox/align-items",
        "tailwind/flexbox/align-self",
        "tailwind/flexbox/place-content",
        "tailwind/flexbox/place-items",
        "tailwind/flexbox/place-self",
      ],
    },
    {
      type: "category",
      label: "Spacing",
      collapsed: false,
      items: [
        "tailwind/spacing/padding",
        "tailwind/spacing/margin",
        "tailwind/spacing/space-between",
      ],
    },
    {
      type: "category",
      label: "Sizing",
      collapsed: false,
      items: [
        "tailwind/sizing/width",
        "tailwind/sizing/min-width",
        "tailwind/sizing/max-width",
        "tailwind/sizing/height",
        "tailwind/sizing/min-height",
        "tailwind/sizing/max-height",
      ],
    },
    {
      type: "category",
      label: "Typography",
      collapsed: false,
      items: [
        "tailwind/typography/font-family",
        "tailwind/typography/font-size",
        "tailwind/typography/font-smoothing",
        "tailwind/typography/font-style",
        "tailwind/typography/font-weight",
        "tailwind/typography/font-variant-numeric",
        "tailwind/typography/letter-spacing",
        "tailwind/typography/line-clamp",
        "tailwind/typography/line-height",
        "tailwind/typography/list-style-image",
        "tailwind/typography/list-style-position",
        "tailwind/typography/list-style-type",
        "tailwind/typography/text-align",
        "tailwind/typography/text-color",
        "tailwind/typography/text-decoration",
        "tailwind/typography/text-decoration-color",
        "tailwind/typography/text-decoration-style",
        "tailwind/typography/text-decoration-thickness",
        "tailwind/typography/text-underline-offset",
        "tailwind/typography/text-transform",
        "tailwind/typography/text-overflow",
        "tailwind/typography/text-ident",
        "tailwind/typography/vertical-align",
        "tailwind/typography/whitespace",
        "tailwind/typography/word-break",
        "tailwind/typography/hyphens",
        "tailwind/typography/content",
      ],
    },
    {
      type: "category",
      label: "Backgrounds",
      collapsed: false,
      items: [
        "tailwind/backgrounds/background-attachment",
        "tailwind/backgrounds/background-clip",
        "tailwind/backgrounds/background-color",
        "tailwind/backgrounds/background-origin",
        "tailwind/backgrounds/background-position",
        "tailwind/backgrounds/background-repeat",
        "tailwind/backgrounds/background-size",
        "tailwind/backgrounds/background-image",
        "tailwind/backgrounds/gradient-color-stops",
      ],
    },
    {
      type: "category",
      label: "Borders",
      collapsed: false,
      items: [
        "tailwind/borders/border-radius",
        "tailwind/borders/border-width",
        "tailwind/borders/border-color",
        "tailwind/borders/border-style",
        "tailwind/borders/divide-width",
        "tailwind/borders/divide-color",
        "tailwind/borders/divide-style",
        "tailwind/borders/outline-width",
        "tailwind/borders/outline-color",
        "tailwind/borders/outline-color",
        "tailwind/borders/outline-offset",
        "tailwind/borders/ring-width",
        "tailwind/borders/ring-color",
        "tailwind/borders/ring-offset-width",
        "tailwind/borders/ring-offset-color",
      ],
    },
    {
      type: "category",
      label: "Effects",
      collapsed: false,
      items: [
        "tailwind/effects/box-shadow",
        "tailwind/effects/box-shadow-color",
        "tailwind/effects/opacity",
        "tailwind/effects/mix-blend-mode",
        "tailwind/effects/background-blend-mode",
      ],
    },
    {
      type: "category",
      label: "Filters",
      collapsed: false,
      items: [
        "tailwind/filters/blur",
        "tailwind/filters/brightness",
        "tailwind/filters/contrast",
        "tailwind/filters/drop-shadow",
        "tailwind/filters/grayscale",
        "tailwind/filters/hue-rotate",
        "tailwind/filters/invert",
        "tailwind/filters/saturate",
        "tailwind/filters/sepia",
        "tailwind/filters/backdrop-blur",
        "tailwind/filters/backdrop-brightness",
        "tailwind/filters/backdrop-contrast",
        "tailwind/filters/backdrop-grayscale",
        "tailwind/filters/backdrop-hue-rotate",
        "tailwind/filters/backdrop-invert",
        "tailwind/filters/backdrop-opacity",
        "tailwind/filters/backdrop-saturate",
        "tailwind/filters/backdrop-sepia",
      ],
    },
    {
      type: "category",
      label: "Tables",
      collapsed: false,
      items: [
        "tailwind/tables/border-collapse",
        "tailwind/tables/border-spacing",
        "tailwind/tables/table-layout",
        "tailwind/tables/caption-side",
      ],
    },
    {
      type: "category",
      label: "Transitions & Animation",
      collapsed: false,
      items: [
        "tailwind/transitions-animation/transition-property",
        "tailwind/transitions-animation/transition-duration",
        "tailwind/transitions-animation/transition-timing-function",
        "tailwind/transitions-animation/transition-delay",
        "tailwind/transitions-animation/animation",
      ],
    },
    {
      type: "category",
      label: "Transforms",
      collapsed: false,
      items: [
        "tailwind/transforms/scale",
        "tailwind/transforms/rotate",
        "tailwind/transforms/translate",
        "tailwind/transforms/skew",
        "tailwind/transforms/transform-origin",
      ],
    },
    {
      type: "category",
      label: "Interactivity",
      collapsed: false,
      items: [
        "tailwind/interactivity/accent-color",
        "tailwind/interactivity/appearance",
        "tailwind/interactivity/cursor",
        "tailwind/interactivity/caret-color",
        "tailwind/interactivity/pointer-events",
        "tailwind/interactivity/resize",
        "tailwind/interactivity/scroll-behaviour",
        "tailwind/interactivity/scroll-margin",
        "tailwind/interactivity/scroll-padding",
        "tailwind/interactivity/scroll-snap-align",
        "tailwind/interactivity/scroll-snap-stop",
        "tailwind/interactivity/scroll-snap-type",
        "tailwind/interactivity/touch-action",
        "tailwind/interactivity/user-select",
        "tailwind/interactivity/will-change",
      ],
    },
    {
      type: "category",
      label: "SVG",
      collapsed: false,
      items: [
        "tailwind/svg/fill",
        "tailwind/svg/stroke",
        "tailwind/svg/stroke-width",
      ],
    },
    {
      type: "category",
      label: "Accessibility",
      collapsed: false,
      items: ["tailwind/accessibility/screen-readers"],
    },
    {
      type: "category",
      label: "Plugins",
      collapsed: false,
      items: ["tailwind/plugins/container-queries"],
    },
  ],
};
module.exports = sidebars;
